name: SEKGS Daily Cycle

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  run-sekgs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r agents/requirements.txt

    - name: Run crawler
      run: python agents/crawler.py

    - name: Run cleaner
      run: python agents/cleaner.py

    - name: Run mapper
      run: python agents/mapper.py

    - name: Run relationer
      run: python agents/relationer.py

    - name: Run optimizer
      run: python agents/optimizer.py

    - name: Run publisher
      run: python agents/publisher.py

    - name: Commit generated data
      run: |
        git config --global user.email "bot@github.com"
        git config --global user.name "SEKGS Bot"
        git add data/ reports/
        git commit -m "chore: update graph + reports" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
