name: SEKGS Actions Test

on:
  workflow_dispatch:

jobs:
  sanity-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print environment info
        run: |
          echo "=== SEKGS ACTIONS TEST ==="
          echo "USER: $(whoami || echo unknown)"
          echo "PWD: $(pwd)"
          echo "List root files:"
          ls -la

      - name: Create quick artifact
        run: |
          mkdir -p reports
          echo "test-ok-$(date -u +%Y%m%dT%H%M%SZ)" > reports/test.txt
          echo "WROTE reports/test.txt"

      - name: Show reports
        run: |
          ls -la reports || true
          cat reports/test.txt || true